In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn import preprocessing, model_selection, feature_selection
from sklearn.decomposition import PCA
import mytrain_lib_cluster as ml
import goalnets as gn
import os

In [78]:
(np.ones(25)*5).astype(int)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5])

In [86]:
import importlib
importlib.reload(ml)

dataset = 'historical_longterm'
drop = ['15D']
regression = False

config = {
    'root':'experiment_regression',
    'train_data':ml.FootballMatchesDataset('train',dataset,drop=drop,factor=-1, regression=regression),
    'test_data':ml.FootballMatchesDataset('test',dataset,drop=drop,factor=-1, regression=regression),
    'model':{
        'model': gn.dumbmodelclass,
        'params':{
            'hidden_neurons':(np.ones(25)*5).astype(int),
            'activation': F.relu,
            'output_classes': 2 if regression else 3,
            'activ_opt':{
                'negative_slope':0.
            },
            'loss_weights':torch.tensor([1.6,1.,1.3]),
            'initialization':False,
            # 'p':0.136341944633018
        }
    },
    'optimizer':{
        'optimizer':torch.optim.SGD,
        'params':{
            'momentum':0,
            'weight_decay':0,
            'nesterov':0,
            'dampening':0.161764655710075,
            'lr':0.001
        }
    },
    'criterion':nn.CrossEntropyLoss,
    'scalers':preprocessing.StandardScaler,
    'batch_size':32,
    'epochs':20,
    'save_outputs':False,
    'display':True,
    'logs':False,
}

In [87]:
config['train_data'].labels

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        ...,
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.]])

In [88]:
import importlib
importlib.reload(ml)
importlib.reload(gn)
ml.Tuning(**config)

Config: 1/1: loss train: 1.35, accuracy train: 0.46, loss test: 1.35, accuracy test: 0.46		: 0.46


1

In [ ]:
aux = torch.tensor([])

In [ ]:
aux = torch.cat((aux,torch.tensor([1,5,6]).reshape(1,-1)),0)
aux

tensor([[1., 5., 6.],
        [1., 5., 6.],
        [1., 5., 6.],
        [1., 5., 6.],
        [1., 5., 6.],
        [1., 5., 6.],
        [1., 5., 6.],
        [1., 5., 6.],
        [1., 5., 6.],
        [1., 5., 6.],
        [1., 5., 6.]])

In [ ]:
torch.tensor([1,2,3]).reshape(1,-1)

tensor([[1, 2, 3]])